name: Flask-IPAM
services:
  flask-ipam:
    image: fipam_docker
    container_name: flask-ipam
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - flask-ipam:/fipam/instance

volumes:
  flask-ipam:
