name: Docker Image CI

on:
  push:
    branches: [ "PROD" ]
  pull_request:
    branches: [ "PROD" ]

jobs:

  build:

    runs-on: python:3.13.2-alpine3.21

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
